springdoc:
  swagger-ui:
    path: /swagger-ui.html
    doc-expansion: none
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  paths-to-match: /**
project:
  default:
    url:
    url_hover:
  openapi:
    dev-url: "http://localhost:9996"
    prod-url: "https://cloud.ha-soft.vn"
spring:
  application:
    name: upload-service
  key:
    name: 20260511upload
  profiles:
    active: "local"
  main:
    allow-circular-references: true
  flyway:
    enabled: true
  folder:
    download: "/app/uploads/"
    uploads: "/app/uploads/"
  servlet:
    multipart:
      max-file-size: 50000KB
      max-request-size: 50000KB